# Niri Theme: sunrise - Soft Sunrise
[colors]
background = "#f0f0f0"
text = "#1a1a1a"
cursor = "#ff7f7f"

[colors.selection]
border = "#a9b6d1"
background = "#e4e3e3"

[colors.hints]
start = "#d5c9a5"
end = "#ffd87a"
