# Niri Theme: midnight - Midnight Cat
[colors]
background = "#121226"
text = "#ffffff"
cursor = "#3c3c86"

[colors.selection]
border = "#7d62ac"
background = "#191b38"

[colors.hints]
start = "#7e4e9d"
end = "#5050a5"
