# Niri Theme: sesame street - Sesame Street
[colors]
background = "#1e3b99"
text = "#ffffff"
cursor = "#7ecd3d"

[colors.selection]
border = "#ec6431"
background = "#204bb0"

[colors.hints]
start = "#f99024"
end = "#f1c84b"
