# Niri Theme: summer rain - Summer Rain
[colors]
background = "#4eb8e9"
text = "#1a1a1a"
cursor = "#4bb9d2"

[colors.selection]
border = "#f4fe49"
background = "#35a5e8"

[colors.hints]
start = "#89d297"
end = "#81c3d0"
