# Niri Theme: prince - Evil Princess Twilight Sparkle
[colors]
background = "#691c7d"
text = "#ffffff"
cursor = "#9c4d9d"

[colors.selection]
border = "#fadec2"
background = "#751f94"

[colors.hints]
start = "#f7d9e2"
end = "#d883b4"
