# Niri Theme: ocean - Midnight Ocean
[colors]
background = "#50437a"
text = "#ffffff"
cursor = "#4b49bc"

[colors.selection]
border = "#58d251"
background = "#564a8d"

[colors.hints]
start = "#d14bd8"
end = "#3236b3"
