# Niri Theme: campfire - Campfire Scary Stories
[colors]
background = "#bf513b"
text = "#ffffff"
cursor = "#f6a65a"

[colors.selection]
border = "#ab7f4f"
background = "#ca5749"

[colors.hints]
start = "#f5bb84"
end = "#f6d55a"
