# Niri Theme: bluey - Bluey Spookie
[colors]
background = "#1b4074"
text = "#ffffff"
cursor = "#4b6faa"

[colors.selection]
border = "#f0f3ff"
background = "#21679c"

[colors.hints]
start = "#8269b5"
end = "#7a9cd1"
