# Niri Theme: bleu - Bleu Bliss
[colors]
background = "#2371e7"
text = "#ffffff"
cursor = "#2891e6"

[colors.selection]
border = "#6c8cef"
background = "#388aec"

[colors.hints]
start = "#60e6b5"
end = "#37a9e6"
