# Niri Theme: 1969 - 1969 Clown
[colors]
background = "#ff6d1f"
text = "#ffffff"
cursor = "#faa700"

[colors.selection]
border = "#d60022"
background = "#ff6b05"

[colors.hints]
start = "#cc8105"
end = "#ffd900"
