# Niri Theme: naked - Cool Palette
[colors]
background = "#f2d4c4"
text = "#1a1a1a"
cursor = "#da7d3e"

[colors.selection]
border = "#ad8e43"
background = "#eec8ae"

[colors.hints]
start = "#cb9152"
end = "#d9a76d"
