# Niri Theme: seattle - Seattle
[colors]
background = "#2f4b7f"
text = "#ffffff"
cursor = "#4b6ba0"

[colors.selection]
border = "#f4f646"
background = "#345b94"

[colors.hints]
start = "#7e65ae"
end = "#7a9db8"
