# Niri Theme: blackout - Blackout Poetry
[colors]
background = "#1c1c1c"
text = "#ffffff"
cursor = "#7a7a7a"

[colors.selection]
border = "#d6ff00"
background = "#343132"

[colors.hints]
start = "#8e8e8e"
end = "#b3b3b3"
