# Niri Theme: waffles - Waffles
[colors]
background = "#e5c080"
text = "#1a1a1a"
cursor = "#f1d66a"

[colors.selection]
border = "#bc9e25"
background = "#e1c45b"

[colors.hints]
start = "#bb782f"
end = "#f5b85b"
