# Niri Theme: Philadelphia Union
[colors]
background = "#071B2C"
text = "#ffffff"
cursor = "#419fee"

[colors.selection]
border = "#7f9900"
background = "#0a2c43"

[colors.hints]
start = "#1c0099"
end = "#B49759"
