# Niri Theme: farmhouse - Farmhouse Chic
[colors]
background = "#f4e2c3"
text = "#1a1a1a"
cursor = "#bc7d4d"

[colors.selection]
border = "#4f4831"
background = "#efde9f"

[colors.hints]
start = "#bfa087"
end = "#a68a7d"
