# Niri Theme: lead - Verdant Leadership
[colors]
background = "#5b9a78"
text = "#ffffff"
cursor = "#51c04f"

[colors.selection]
border = "#de9345"
background = "#4f8c6f"

[colors.hints]
start = "#f19a27"
end = "#e3e368"
