# Niri Theme: slate - Slate Blue Shadows
[colors]
background = "#7a8c99"
text = "#ffffff"
cursor = "#5a7e8c"

[colors.selection]
border = "#17304f"
background = "#627288"

[colors.hints]
start = "#315e49"
end = "#3a6f7e"
