# Niri Theme: Philadelphia Phillies
[colors]
background = "#002D72"
text = "#ffffff"
cursor = "#1874ff"

[colors.selection]
border = "#94d800"
background = "#003f8c"

[colors.hints]
start = "#4600d8"
end = "#7691d2"
