# Niri Theme: matrix - Matrix Green
[colors]
background = "#00b300"
text = "#ffffff"
cursor = "#30db00"

[colors.selection]
border = "#a8fff6"
background = "#0ccc00"

[colors.hints]
start = "#8cf90b"
end = "#4dff5b"
