# Niri Theme: earthy - Earthy Elegance
[colors]
background = "#f2f2f2"
text = "#1a1a1a"
cursor = "#c0b0a0"

[colors.selection]
border = "#3d1d0b"
background = "#e6e5e5"

[colors.hints]
start = "#ab9b8c"
end = "#a79c7b"
