# Niri Theme: herb - Herbology
[colors]
background = "#7c9b4b"
text = "#ffffff"
cursor = "#a3c57d"

[colors.selection]
border = "#88cb5d"
background = "#6a8c41"

[colors.hints]
start = "#d5e175"
end = "#a4d463"
