# Niri Theme: hippies - Musicos Hippies
[colors]
background = "#f6c80e"
text = "#1a1a1a"
cursor = "#f17c22"

[colors.selection]
border = "#4468d9"
background = "#e4c606"

[colors.hints]
start = "#d66b14"
end = "#e73e27"
