# Niri Theme: pirates - Pirates
[colors]
background = "#3c2a2a"
text = "#ffffff"
cursor = "#ad7070"

[colors.selection]
border = "#f9ecae"
background = "#4c3335"

[colors.hints]
start = "#dbc2a4"
end = "#a67c6e"
