# Niri Theme: sage - Sage Serenity
[colors]
background = "#a7c8b9"
text = "#1a1a1a"
cursor = "#6f9b7f"

[colors.selection]
border = "#1c4c50"
background = "#96c0af"

[colors.hints]
start = "#657f62"
end = "#4b8166"
