# Niri Theme: asteroid - Asteroid Contrast
[colors]
background = "#4a4e68"
text = "#ffffff"
cursor = "#f0a400"

[colors.selection]
border = "#819cb1"
background = "#535a79"

[colors.hints]
start = "#f5c88a"
end = "#f6bc60"
