# Niri Theme: english breakfast - English Breakfast
[colors]
background = "#d96030"
text = "#ffffff"
cursor = "#f4a462"

[colors.selection]
border = "#375faa"
background = "#df6643"

[colors.hints]
start = "#f3bb8b"
end = "#e8c468"
