# Niri Theme: mossy oak - Mossy Oak Cabin
[colors]
background = "#4b3c2a"
text = "#ffffff"
cursor = "#7a6e5c"

[colors.selection]
border = "#f2f5d1"
background = "#6b4c38"

[colors.hints]
start = "#e3d5c4"
end = "#b1a98c"
