# Niri Theme: tupac - Tupac
[colors]
background = "#2b3d50"
text = "#ffffff"
cursor = "#e74d3c"

[colors.selection]
border = "#2d58e1"
background = "#324c62"

[colors.hints]
start = "#f0a53e"
end = "#f39c12"
