# Niri Theme: noon - Noon Duskbright
[colors]
background = "#ffb300"
text = "#1a1a1a"
cursor = "#ff6e00"

[colors.selection]
border = "#99179c"
background = "#e6af00"

[colors.hints]
start = "#d16005"
end = "#d54215"
