# Niri Theme: maraschino - Maraschino Delight
[colors]
background = "#c6102e"
text = "#ffffff"
cursor = "#d61f3a"

[colors.selection]
border = "#ffb48a"
background = "#e0103e"

[colors.hints]
start = "#fc9688"
end = "#f52941"
