# Niri Theme: dracula - Draculaura
[colors]
background = "#ff75a8"
text = "#1a1a1a"
cursor = "#d06c9b"

[colors.selection]
border = "#603771"
background = "#ff5b8e"

[colors.hints]
start = "#c0536c"
end = "#a66492"
