# Niri Theme: mint chocolate chip - Mint Chocolate Chip
[colors]
background = "#b2e6d4"
text = "#1a1a1a"
cursor = "#57c17e"

[colors.selection]
border = "#81d088"
background = "#9de1ce"

[colors.hints]
start = "#aca091"
end = "#c1b6a4"
