# Niri Theme: vaporwave - Vaporwave
[colors]
background = "#ff75ff"
text = "#1a1a1a"
cursor = "#3dffec"

[colors.selection]
border = "#0fffb9"
background = "#ff5bf5"

[colors.hints]
start = "#ff0f53"
end = "#ffce5c"
