# Niri Theme: lakers -  Lakers Vibes
[colors]
background = "#5523b8"
text = "#ffffff"
cursor = "#9c3cb4"

[colors.selection]
border = "#db6443"
background = "#5425d0"

[colors.hints]
start = "#e7b574"
end = "#e6a84c"
