# Niri Theme: morning coffee - Morning Coffee Mood
[colors]
background = "#6f4c3e"
text = "#ffffff"
cursor = "#d8b49d"

[colors.selection]
border = "#bccfa0"
background = "#815345"

[colors.hints]
start = "#e8d7c4"
end = "#e0c5a3"
