# Niri Theme: ashes - Burning Ashes
[colors]
background = "#7d4a26"
text = "#ffffff"
cursor = "#c96936"

[colors.selection]
border = "#e4e3e2"
background = "#a34d2e"

[colors.hints]
start = "#f6b15b"
end = "#f9a52f"
