# Niri Theme: Rose Pine Official
[colors]
background = "#191724"
text = "#ffffff"
cursor = "#eb6f92"

[colors.selection]
border = "#347b26"
background = "#222034"

[colors.hints]
start = "#73247d"
end = "#ebbcba"
