# Niri Theme: henry - Henry the VII
[colors]
background = "#6c4f3d"
text = "#ffffff"
cursor = "#c9b8a1"

[colors.selection]
border = "#df6620"
background = "#7e5744"

[colors.hints]
start = "#dab79a"
end = "#d3a078"
