# Niri Theme: terra cotta - Terra Cotta Fusion
[colors]
background = "#f5e0a8"
text = "#1a1a1a"
cursor = "#f1b341"

[colors.selection]
border = "#a47137"
background = "#f3e581"

[colors.hints]
start = "#d56a25"
end = "#e47b3f"
