# Niri Theme: eagles - Early Eagles
[colors]
background = "#f1c40e"
text = "#1a1a1a"
cursor = "#e77e23"

[colors.selection]
border = "#b33dac"
background = "#cec409"

[colors.hints]
start = "#c56b1c"
end = "#e74d3c"
