# Niri Theme: coal - Blush and Charcoal
[colors]
background = "#f0a3b9"
text = "#1a1a1a"
cursor = "#3b2b2b"

[colors.selection]
border = "#3c0b1b"
background = "#ee8ca2"

[colors.hints]
start = "#221c1b"
end = "#6f4d4d"
