# Niri Theme: notre dame - Notre Dame
[colors]
background = "#5b3a39"
text = "#ffffff"
cursor = "#a85f2e"

[colors.selection]
border = "#3b41d3"
background = "#6c4142"

[colors.hints]
start = "#c2753d"
end = "#e0b65c"
