# Niri Theme: dark sage - Dark Sage
[colors]
background = "#5b806e"
text = "#ffffff"
cursor = "#a3baa0"

[colors.selection]
border = "#f9faef"
background = "#639178"

[colors.hints]
start = "#c1c8bb"
end = "#c2d6c6"
