# Niri Theme: sno cone - Sno Cone
[colors]
background = "#ff6e61"
text = "#ffffff"
cursor = "#ffb84d"

[colors.selection]
border = "#ccff3d"
background = "#ff6247"

[colors.hints]
start = "#faa02a"
end = "#4eb7ac"
