# Niri Theme: olive oil - Olive Oil
[colors]
background = "#a4b65d"
text = "#1a1a1a"
cursor = "#d2c670"

[colors.selection]
border = "#7d7335"
background = "#94ae4b"

[colors.hints]
start = "#d8aa7e"
end = "#dc8b3d"
