# Niri Theme: pikachu - Pikachu Blush
[colors]
background = "#efe0b8"
text = "#1a1a1a"
cursor = "#e7c465"

[colors.selection]
border = "#9648f9"
background = "#ebdca2"

[colors.hints]
start = "#abfe43"
end = "#e7bb65"
