# Niri Theme: gray moon - Dark Gray Moon
[colors]
background = "#2b2933"
text = "#ffffff"
cursor = "#786d92"

[colors.selection]
border = "#e3dfe6"
background = "#3c3b4f"

[colors.hints]
start = "#d1ccd2"
end = "#7a7882"
