# Niri Theme: phillies - Red and Blue Phillies
[colors]
background = "#d60032"
text = "#ffffff"
cursor = "#00e05e"

[colors.selection]
border = "#1005ff"
background = "#ff0565"

[colors.hints]
start = "#f4be67"
end = "#ffffff"
