# Niri Theme: mars - Hot Chocolate & Marshmallow
[colors]
background = "#5e3a2c"
text = "#ffffff"
cursor = "#d18f6b"

[colors.selection]
border = "#f5bd9e"
background = "#714032"

[colors.hints]
start = "#d7aa8e"
end = "#f1e7cb"
