# Niri Theme: salmon - Salmon Bliss
[colors]
background = "#ffa05c"
text = "#1a1a1a"
cursor = "#ff7029"

[colors.selection]
border = "#ffb057"
background = "#ffa733"

[colors.hints]
start = "#ff9a4c"
end = "#ff8647"
