# Niri Theme: the office - The Office
[colors]
background = "#3c3f44"
text = "#ffffff"
cursor = "#8a9a5b"

[colors.selection]
border = "#9f59a1"
background = "#464c53"

[colors.hints]
start = "#fcd188"
end = "#ffcb5c"
