# Niri Theme: christmas - Christmas
[colors]
background = "#a52c2e"
text = "#ffffff"
cursor = "#d9b34a"

[colors.selection]
border = "#dc7846"
background = "#bb2f3a"

[colors.hints]
start = "#dcb870"
end = "#f2f6d5"
