# Niri Theme: boobs - Boobs
[colors]
background = "#ff6e61"
text = "#ffffff"
cursor = "#ff4024"

[colors.selection]
border = "#fff78a"
background = "#ff6247"

[colors.hints]
start = "#ff8247"
end = "#ff613d"
