# Niri Theme: monster truck - Monster Truck
[colors]
background = "#445550"
text = "#ffffff"
cursor = "#77b757"

[colors.selection]
border = "#e47b44"
background = "#557165"

[colors.hints]
start = "#f7ac59"
end = "#d1d425"
