# Niri Theme: civil war - The Civil War
[colors]
background = "#a62b2b"
text = "#ffffff"
cursor = "#d2691e"

[colors.selection]
border = "#46d8ba"
background = "#bd2e36"

[colors.hints]
start = "#dd823c"
end = "#ffd900"
