# Niri Theme: philadelphia - Philadelphia Sunrise
[colors]
background = "#699ebf"
text = "#ffffff"
cursor = "#4b9bd2"

[colors.selection]
border = "#4e4a54"
background = "#558dba"

[colors.hints]
start = "#faa02a"
end = "#ffb84d"
