# Niri Theme: Philadelphia 76ers
[colors]
background = "#264c66"
text = "#ffffff"
cursor = "#53a7e1"

[colors.selection]
border = "#728ce0"
background = "#2b5f7a"

[colors.hints]
start = "#5bedbd"
end = "#aac7dc"
