# Niri Theme: khaki - Khaki Dreams
[colors]
background = "#c4bcb1"
text = "#1a1a1a"
cursor = "#a79f7b"

[colors.selection]
border = "#514c2a"
background = "#bbb1a1"

[colors.hints]
start = "#4f4437"
end = "#8a7b56"
