# Niri Theme: macadam - Macadamia Nut Delight
[colors]
background = "#d5cec3"
text = "#1a1a1a"
cursor = "#b8aa9d"

[colors.selection]
border = "#928449"
background = "#c6bfa9"

[colors.hints]
start = "#a2968b"
end = "#d79b4c"
