# Niri Theme: char - Coquette Charm
[colors]
background = "#f1bbca"
text = "#1a1a1a"
cursor = "#e96d82"

[colors.selection]
border = "#c95c45"
background = "#eea5b5"

[colors.hints]
start = "#de4f51"
end = "#d97299"
