# Niri Theme: fallen angel - Fallen Angel
[colors]
background = "#4b3d5c"
text = "#ffffff"
cursor = "#a26d8b"

[colors.selection]
border = "#fbf5a7"
background = "#55456d"

[colors.hints]
start = "#faf3eb"
end = "#f2a6ba"
