# Niri Theme: s'mores - Cool Palette
[colors]
background = "#3b3030"
text = "#ffffff"
cursor = "#a26a4e"

[colors.selection]
border = "#bc9957"
background = "#4a3a3b"

[colors.hints]
start = "#ecd8c6"
end = "#e4c4a5"
