# Niri Theme: burnt - Burnt Blue
[colors]
background = "#3a4b78"
text = "#ffffff"
cursor = "#4d6b99"

[colors.selection]
border = "#e7f2b0"
background = "#466a9a"

[colors.hints]
start = "#7c66a9"
end = "#79a2c3"
