# Niri Theme: storm - Stormy Lavender Dreams
[colors]
background = "#6b5b8b"
text = "#ffffff"
cursor = "#9a79af"

[colors.selection]
border = "#f3bfd4"
background = "#73639d"

[colors.hints]
start = "#ffffff"
end = "#d6c3e9"
