#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["requests"]
# ///
"""
auto-theme — Unified theme generator and activator.

Modes:
1. Team Mode: Uses existing teamcolors-full.json (e.g., "lakers", "flyers")
2. API Mode: Fetches palettes from Color Magic API for keywords (e.g., "neapolitan", "halloween")

Usage:
    python3 scripts/auto-theme.py "Philadelphia 76ers"       # Team mode
    python3 scripts/auto-theme.py "neapolitan"               # API mode (Ice cream)
    python3 scripts/auto-theme.py "halloween"                # API mode (Holiday)
    python3 scripts/auto-theme.py --list                     # List available teams
    python3 scripts/auto-theme.py --list-api "tropical"      # Preview API results
"""

import argparse
import colorsys
import json
import os
import re
import subprocess
import sys
import unicodedata
import hashlib
from pathlib import Path
from datetime import datetime
from string import Template

# External dependency for API
try:
    import requests
except ImportError:
    print("❌ Error: 'requests' library not found. Install with: pip install requests")
    sys.exit(1)

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent
NIXOS_ROOT = SCRIPT_DIR.parent
TEAMS_DIR = NIXOS_ROOT / "themes" / "Teams"
API_CACHE_FILE = NIXOS_ROOT / "scripts" / "api-palette-cache.json"
TEAM_DATA_FILE = NIXOS_ROOT / "scripts" / "teamcolors-full.json"
MAKE_WALLPAPER = NIXOS_ROOT / "scripts" / "make-lix-wallpaper.sh"
COLOR_MAGIC_API = "https://colormagic.app/api/palette/search"

# ── Layout constants (mirror of themes/layout.nix) ───────────────────────────
LAYOUT = {
    "RADIUS_SM":     6,
    "RADIUS_MD":     8,
    "RADIUS_LG":     12,
    "GAP":           6,
    "BORDER_W":      2,
    "SHADOW_BLUR":   10,
    "SHADOW_SPREAD": -1,
}

# ── Waybar CSS Template (port of home/waybar/style.nix) ───────────────────────
# Uses string.Template ${KEY} placeholders; constant alpha/size values
# are injected by generate_waybar_css so the palette dict doesn't need them.
# Layout numeric values (radius, shadow) are baked in via .replace() below.
_RM = LAYOUT["RADIUS_MD"]
_RL = LAYOUT["RADIUS_LG"]
_RS = LAYOUT["RADIUS_SM"]
_SB = LAYOUT["SHADOW_BLUR"]
_SP = LAYOUT["SHADOW_SPREAD"]

_WAYBAR_CSS_TEMPLATE = """\
/* ============================================================
 * WAYBAR — PAPERCRAFT THEME (auto-generated by auto-theme.py)
 * Flat paper bubble aesthetic: hard offset shadows, bold borders.
 * Shadow shrinks on hover — the "paper pressed down" effect.
 * ============================================================ */

window#waybar {
  background: transparent;
  font-family: "JetBrainsMono Nerd Font", "JetBrains Mono", "Maple Mono", "Noto Sans Mono", monospace;
  font-size: ${FONT_SIZE_BAR};
  color: ${TEXT};
}

.module {
  background: ${WB_SURFACE};
  color: ${TEXT};
  padding: 4px 14px;
  margin: 5px 3px;
  border-radius: 8px;
  border: 2px solid ${SHADOW};
  box-shadow: 3px 4px 0 0 ${SHADOW};
  transition: background 0.10s ease, box-shadow 0.10s ease;
}

.module:hover {
  background: ${WB_OVERLAY};
  color: ${TEXT};
  box-shadow: 2px 3px 0 0 ${SHADOW};
}

#custom-clock,
#custom-battery {
  background: ${WB_OVERLAY};
}

#custom-weather,
#custom-cpu_temp,
#custom-volume,
#custom-mpris {
  background: ${WB_SURFACE};
}

#custom-network,
#custom-bluetooth,
#tray {
  background: ${WB_BASE};
}

#custom-start {
  color: ${IRIS};
  background: ${WB_OVERLAY};
  border-color: ${LOVE};
  font-weight: 600;
  letter-spacing: 0.04em;
  padding-left: 16px;
  padding-right: 16px;
}
#custom-start:hover {
  color: ${TEXT};
  background: ${OVERLAY};
  border-color: ${LOVE};
  box-shadow: 2px 3px 0 0 ${SHADOW};
}

#custom-clock          { font-weight: 600; letter-spacing: 0.05em; color: ${TEXT}; }
#custom-clock:hover    { color: ${TEXT}; background: ${OVERLAY}; }

#custom-weather        { color: ${MUTED_ICON}; }
#custom-weather:hover  { color: ${TEXT}; background: ${OVERLAY}; }

#custom-cpu_temp               { color: ${MUTED_ICON}; }
#custom-cpu_temp.cool:hover     { color: ${FOAM}; }
#custom-cpu_temp.warm:hover     { color: ${CAUTION}; }
#custom-cpu_temp.hot:hover      { color: ${WARNING}; }
#custom-cpu_temp.critical:hover { color: ${CRITICAL}; }

#custom-battery                { color: ${MUTED_ICON}; }
#custom-battery.full:hover     { color: ${FOAM}; }
#custom-battery.high:hover     { color: #7ab3c0; }
#custom-battery.medium:hover   { color: #a0d44e; }
#custom-battery.low:hover      { color: ${WARNING}; }
#custom-battery.critical:hover { color: ${CRITICAL}; }

#custom-volume         { color: ${MUTED_ICON}; }
#custom-volume.muted   { color: ${MUTED}; }

#custom-volume.muted:hover,
#custom-volume.vol-0:hover   { background: ${HOVER_MUTED_BG}; color: ${MUTED}; }
#custom-volume.vol-5:hover   { background: ${HOVER_TEAL_BG}; color: #6e9aa8; }
#custom-volume.vol-10:hover  { background: ${HOVER_TEAL_BG}; color: #7ab3c0; }
#custom-volume.vol-15:hover  { background: ${HOVER_TEAL_BG}; color: #8ac8d4; }
#custom-volume.vol-20:hover  { background: ${TINT_PINE_MID}; color: ${FOAM}; }
#custom-volume.vol-25:hover  { background: ${TINT_PINE_MID}; color: ${FOAM}; }
#custom-volume.vol-30:hover  { background: ${TINT_PINE_DARK}; color: ${FOAM}; }
#custom-volume.vol-35:hover  { background: ${HOVER_GREEN_BG}; color: #7ecba8; }
#custom-volume.vol-40:hover  { background: ${HOVER_GREEN_BG}; color: #6dc99a; }
#custom-volume.vol-45:hover  { background: ${HOVER_GREEN_BG}; color: #5ec88c; }
#custom-volume.vol-50:hover  { background: ${HOVER_GREEN_BG}; color: #72cc6a; }
#custom-volume.vol-55:hover  { background: ${HOVER_GREEN_BG}; color: #a0d44e; }
#custom-volume.vol-60:hover  { background: ${HOVER_GOLD_BG}; color: ${CAUTION}; }
#custom-volume.vol-65:hover  { background: ${HOVER_GOLD_BG}; color: #ddd028; }
#custom-volume.vol-70:hover  { background: ${HOVER_ORANGE_BG}; color: #f0c020; }
#custom-volume.vol-75:hover  { background: ${HOVER_ORANGE_BG}; color: ${GOLD}; }
#custom-volume.vol-80:hover  { background: ${TINT_CRITICAL_BG}; color: #d94f3a; }
#custom-volume.vol-85:hover  { background: ${TINT_CRITICAL_BG}; color: #c0302a; }
#custom-volume.vol-90:hover  { background: ${TINT_CRITICAL_BG}; color: #b82020; }
#custom-volume.vol-95:hover  { background: ${TINT_CRITICAL_BG}; color: #e0306a; }
#custom-volume.vol-100:hover { background: ${TINT_CRITICAL_BG}; color: ${CRITICAL}; border-color: ${LOVE}; }

#custom-mpris              { color: ${MUTED_ICON}; }
#custom-mpris.playing      { color: ${FOAM}; }
#custom-mpris.paused       { color: ${SUBTLE}; }
#custom-mpris.stopped      { opacity: 0.45; }
#custom-mpris:hover        { color: ${TEXT}; background: ${OVERLAY}; }

#custom-sqlch              { color: ${MUTED_ICON}; }
#custom-sqlch.playing      { color: ${FOAM}; }
#custom-sqlch.paused       { color: ${SUBTLE}; }
#custom-sqlch.idle         { color: ${MUTED}; opacity: 0.6; }
#custom-sqlch.inactive     { opacity: 0.35; }
#custom-sqlch:hover        { color: ${TEXT}; background: ${OVERLAY}; }

#custom-network                    { color: ${MUTED_ICON}; }
#custom-network.wifi.low:hover     { color: ${WARNING}; }
#custom-network.wifi.mid:hover     { color: ${CAUTION}; }
#custom-network.wifi.high:hover    { color: #7ab3c0; }
#custom-network.wifi.full:hover    { color: ${FOAM}; }
#custom-network.wired:hover        { color: ${FOAM}; }
#custom-network.vpn:hover          { color: ${IRIS}; }
#custom-network.offline            { opacity: 0.45; }
#custom-network.offline:hover      { opacity: 0.7; color: ${MUTED}; }

#custom-bluetooth      { color: ${MUTED_ICON}; }
#custom-bluetooth.off  { opacity: 0.45; }
#custom-bluetooth:hover { color: ${TEXT}; }

#custom-btrfs                  { color: ${MUTED_ICON}; }
#custom-btrfs.fresh:hover      { color: ${FOAM}; }
#custom-btrfs.ok:hover         { color: ${CAUTION}; }
#custom-btrfs.warn:hover       { color: ${WARNING}; }
#custom-btrfs.critical:hover   { color: ${CRITICAL}; }

#custom-flake-drift              { color: ${MUTED_ICON}; }
#custom-flake-drift.fresh:hover  { color: ${FOAM}; }
#custom-flake-drift.ok:hover     { color: ${CAUTION}; }
#custom-flake-drift.aging:hover  { color: ${WARNING}; }
#custom-flake-drift.stale:hover  { color: ${CRITICAL}; }

#custom-perf                   { color: ${MUTED_ICON}; }
#custom-perf.idle:hover        { color: ${FOAM}; }
#custom-perf.active:hover      { color: ${CAUTION}; }
#custom-perf.warn:hover        { color: ${WARNING}; }
#custom-perf.critical:hover    { color: ${CRITICAL}; }

#custom-power_profile                  { color: ${MUTED_ICON}; }
#custom-power_profile.power-saver      { color: ${FOAM}; }
#custom-power_profile.performance      { color: ${LOVE}; }
#custom-power_profile:hover            { color: ${TEXT}; }

#custom-idle_inhibit           { color: ${MUTED_ICON}; }
#custom-idle_inhibit.active    { color: ${FOAM}; }
#custom-idle_inhibit.inhibited { color: ${MUTED}; opacity: 0.6; }
#custom-idle_inhibit:hover     { color: ${TEXT}; opacity: 1; }

#custom-dnd          { color: ${MUTED_ICON}; }
#custom-dnd.dnd      { color: ${GOLD}; }
#custom-dnd:hover    { color: ${TEXT}; }

#custom-utilities-handle       { color: ${MUTED}; }
#custom-utilities-handle:hover { color: ${MUTED_ICON}; }
#custom-choose_mode            { color: ${MUTED_ICON}; }
#custom-choose_mode:hover      { color: ${TEXT}; }

#custom-wleave       { color: ${MUTED_ICON}; }
#custom-wleave:hover { color: ${LOVE}; }

#custom-uniremote       { color: ${MUTED_ICON}; }
#custom-uniremote:hover { color: ${TEXT}; }

#toggles {
  background: ${WB_BASE};
  border: 2px solid ${SHADOW};
  border-radius: 12px;
  margin: 5px 3px;
  padding: 0;
  box-shadow: 3px 4px 0 0 ${SHADOW};
  transition: background 0.10s ease, box-shadow 0.10s ease;
}
#toggles:hover {
  background: ${WB_OVERLAY};
  box-shadow: 2px 3px 0 0 ${SHADOW};
}

#connectivity {
  background: ${WB_BASE};
  border: 2px solid ${SHADOW};
  border-radius: 12px;
  margin: 5px 3px;
  padding: 0;
  box-shadow: 3px 4px 0 0 ${SHADOW};
  transition: background 0.10s ease, box-shadow 0.10s ease;
}
#connectivity:hover {
  background: ${WB_OVERLAY};
  box-shadow: 2px 3px 0 0 ${SHADOW};
}

#actions {
  background: ${WB_BASE};
  border: 2px solid ${SHADOW};
  border-radius: 12px;
  margin: 5px 3px;
  padding: 0;
  box-shadow: 3px 4px 0 0 ${SHADOW};
  transition: background 0.10s ease, box-shadow 0.10s ease;
}
#actions:hover {
  background: ${WB_OVERLAY};
  box-shadow: 2px 3px 0 0 ${SHADOW};
}

#system-stats {
  background: ${WB_OVERLAY};
  border: 2px solid ${SHADOW};
  border-radius: 12px;
  margin: 5px 3px;
  padding: 0;
  box-shadow: 3px 4px 0 0 ${SHADOW};
  transition: background 0.10s ease, box-shadow 0.10s ease;
}
#system-stats:hover {
  background: ${OVERLAY};
  box-shadow: 2px 3px 0 0 ${SHADOW};
}

#storage {
  background: ${WB_BASE};
  border: 2px solid ${SHADOW};
  border-radius: 12px;
  margin: 5px 3px;
  padding: 0;
  box-shadow: 3px 4px 0 0 ${SHADOW};
  transition: background 0.10s ease, box-shadow 0.10s ease;
}
#storage:hover {
  background: ${WB_OVERLAY};
  box-shadow: 2px 3px 0 0 ${SHADOW};
}

#toggles > widget > *,
#connectivity > widget > *,
#actions > widget > *,
#system-stats > widget > *,
#storage > widget > * {
  background: transparent;
  border: none;
  border-radius: 10px;
  margin: 0 1px;
  box-shadow: none;
  padding: 4px 10px;
  transition: background 0.10s ease, color 0.10s ease;
}

#toggles > widget > *:hover,
#connectivity > widget > *:hover,
#actions > widget > *:hover,
#system-stats > widget > *:hover,
#storage > widget > *:hover {
  background: rgba(255,255,255,0.12);
  border-radius: 10px;
  box-shadow: none;
  border: none;
}

#toggles > widget:first-child > *,
#connectivity > widget:first-child > *,
#actions > widget:first-child > *,
#system-stats > widget:first-child > *,
#storage > widget:first-child > * { padding-left: 12px; }

#toggles > widget:last-child > *,
#connectivity > widget:last-child > *,
#actions > widget:last-child > *,
#system-stats > widget:last-child > *,
#storage > widget:last-child > *  { padding-right: 12px; }

#workspaces button {
  background: transparent;
  color: ${MUTED};
  padding: 0 7px;
  margin: 0 1px;
  border-radius: 6px;
  border: 2px solid transparent;
  transition: background 0.10s ease, color 0.10s ease;
}

#workspaces button.active {
  background: ${OVERLAY};
  color: ${TEXT};
  border-color: ${LOVE};
  box-shadow: 2px 3px 0 0 ${SHADOW};
}

#workspaces button:hover {
  background: ${GRAD_BASE_HI};
  color: ${MUTED_ICON};
  border-color: ${MUTED};
}

#tray > .passive          { -gtk-icon-effect: dim; }
#tray > .needs-attention  { -gtk-icon-effect: highlight; }

window.background.tooltip {
  background-color: transparent;
  border-radius: 8px;
}

tooltip {
  background: ${tooltipBg};
  border: 2px solid ${SHADOW};
  border-radius: 8px;
  padding: 4px 2px;
  box-shadow: 3px 4px 0 0 ${SHADOW};
}

tooltip label {
  color: ${TEXT};
  font-size: 13px;
  font-weight: 600;
  padding: 3px 10px;
}
"""
# Bake layout constants into the template at module load time.
# Shadow patterns use f-string escaping: ${{KEY}} → ${KEY} (kept as Template placeholder).
_WAYBAR_CSS_TEMPLATE = (
    _WAYBAR_CSS_TEMPLATE
    .replace("  border-radius: 8px;",  f"  border-radius: {_RM}px;")
    .replace("  border-radius: 12px;", f"  border-radius: {_RL}px;")
    .replace("  border-radius: 10px;", f"  border-radius: {_RL - 2}px;")
    .replace("  border-radius: 6px;",  f"  border-radius: {_RS}px;")
    .replace(
        "    0 4px 10px rgba(${SHADOW_RGB},${SHADOW_A_DROP});",
        f"    0 4px {_SB}px {_SP}px rgba(${{SHADOW_RGB}},${{SHADOW_A_DROP}});",
    )
    .replace(
        "    0 4px 12px rgba(${SHADOW_RGB},${SHADOW_A_DROP});",
        f"    0 4px {_SB}px {_SP}px rgba(${{SHADOW_RGB}},${{SHADOW_A_DROP}});",
    )
    .replace(
        "    0 4px 14px rgba(${BORDER_ACCENT_RGB},0.20),",
        f"    0 4px {_SB + 4}px {_SP}px rgba(${{BORDER_ACCENT_RGB}},0.20),",
    )
    .replace(
        "    0 5px 12px rgba(${SHADOW_RGB},${SHADOW_A_HOVER});",
        f"    0 5px {_SB + 2}px {_SP}px rgba(${{SHADOW_RGB}},${{SHADOW_A_HOVER}});",
    )
)

# ── Color Math Helpers (Minimal, no deps) ─────────────────────────────────────

def _hex_to_hsl(h: str) -> tuple[float, float, float]:
    r, g, b = int(h[1:3], 16)/255, int(h[3:5], 16)/255, int(h[5:7], 16)/255
    mx, mn = max(r, g, b), min(r, g, b)
    l = (mx + mn) / 2
    if mx == mn: return 0.0, 0.0, l
    d = mx - mn
    s = d / (2 - mx - mn) if l > 0.5 else d / (mx + mn)
    if mx == r:   hue = (g - b) / d + (6 if g < b else 0)
    elif mx == g: hue = (b - r) / d + 2
    else:         hue = (r - g) / d + 4
    return hue / 6, s, l

def _hsl_to_hex(h: float, s: float, l: float) -> str:
    if s == 0:
        v = round(l * 255)
        return f"#{v:02x}{v:02x}{v:02x}"
    def _hue(p, q, t):
        t %= 1
        if t < 1/6: return p + (q - p) * 6 * t
        if t < 1/2: return q
        if t < 2/3: return p + (q - p) * (2/3 - t) * 6
        return p
    q = l * (1 + s) if l < 0.5 else l + s - l * s
    p = 2 * l - q
    r, g, b = _hue(p, q, h + 1/3), _hue(p, q, h), _hue(p, q, h - 1/3)
    # FIX: Changed the last g to a b[cite: 3]
    return f"#{round(r*255):02x}{round(g*255):02x}{round(b*255):02x}".lower()

def _clamp(val, min_v=0.0, max_v=1.0):
    return max(min_v, min(max_v, val))

def _adjust_color(hex_color: str, l_offset: float = 0, s_offset: float = 0, h_offset: float = 0) -> str:
    """Adjusts HSL with clamping and saturation compensation."""
    h, s, l = _hex_to_hsl(hex_color)

    # 1. Automatic Hue Shifting for depth
    # If we are darkening (l < 0), tilt toward Blue (approx 0.66 in HSL)
    # If we are lightening (l > 0), tilt toward Yellow (approx 0.16 in HSL)
    if l < 0:
        h -= 0.02  # Subtle cool shift
        sat += 0.05 # Prevent muddiness
    elif l > 0:
        h += 0.02  # Subtle warm shift
        sat -= 0.02 # Prevent neon-glow

    return _hsl_to_hex(
        (hue + h) % 1.0,
        max(0.0, min(1.0, sat + s)),
        max(0.0, min(1.0, light + l))
    )

    # 2. Adjust Saturation
    # If we darken significantly, we often want to boost saturation to keep it from looking 'muddy'
    new_s = _clamp(s + s_offset)

    # 3. Adjust Lightness
    new_l = _clamp(l + l_offset)

    return _hsl_to_hex(h, new_s, new_l)

def _get_farthest_hue(hex_color: str) -> str:
    """Returns a high-contrast accent hue using the Golden Ratio."""
    h, s, l = _hex_to_hsl(hex_color)
    # Use the Golden Ratio (approx 0.618) to find a harmonious but distinct hue
    return _hsl_to_hex((h + 0.618033988749895) % 1.0, s, l)

def _get_text_color(hex_color: str) -> str:
    r, g, b = int(hex_color[1:3], 16), int(hex_color[3:5], 16), int(hex_color[5:7], 16)
    brightness = (r * 299 + g * 587 + b * 114) // 1000
    return "#1a1a1a" if brightness > 155 else "#ffffff"

def _theme_mode(hex_color: str) -> str:
    r, g, b = int(hex_color[1:3], 16), int(hex_color[3:5], 16), int(hex_color[5:7], 16)
    brightness = (r * 299 + g * 587 + b * 114) // 1000
    return "dark" if brightness < 128 else "light"

def generate_waybar_css(p: dict) -> str:
    """Substitute palette into the waybar CSS template (port of home/waybar/style.nix)."""
    tooltip_bg = f"rgba({p['OVERLAY_RGB']},0.99)" if 'OVERLAY_RGB' in p else p['WB_BASE']
    # Constants that live in write_nix but are not in the runtime palette dict
    defaults = {
        'FONT_SIZE_BAR': '12px',
        'ICON_SHADOW':   '0 1px 2px rgba(0,0,0,0.80)',
        'SHADOW_A_OUTER': '0.50',
        'SHADOW_A_DROP':  '0.55',
        'SHADOW_A_HOVER': '0.65',
        'INSET_TOP_A':    '0.08',
        'INSET_BOT_A':    '0.30',
        'BORDER_TOP_A':   '0.07',
    }
    vars = {**defaults, **p, 'tooltipBg': tooltip_bg}
    return Template(_WAYBAR_CSS_TEMPLATE).safe_substitute(vars)

# ── API Interaction ───────────────────────────────────────────────────────────

def _adjust(hex_col: str, l: float = 0, s: float = 0, h: float = 0) -> str:
    """Adjusts HSL values with clamping and returns a hex string."""
    hue, sat, light = _hex_to_hsl(hex_col)
    return _hsl_to_hex((hue + h) % 1.0, max(0, min(1, sat + s)), max(0, min(1, light + l)))

def fetch_api_palette(query: str, cache: dict) -> dict | None:
    cache_key = query.lower().strip()
    if cache_key in cache:
        print(f"⏭️  Using cached palette for '{query}'")
        return cache[cache_key]

    url = f"{COLOR_MAGIC_API}?q={query.replace(' ', '+')}"
    try:
        print(f"🔍 Fetching '{query}' from Color Magic API...")
        resp = requests.get(url, timeout=10)
        resp.raise_for_status()
        results = resp.json()

        if not results: return None

        best = max(results, key=lambda x: x.get('likesCount', 0))
        colors = best['colors']
        if len(colors) < 5: return None

        # 1. Map the 5 base colors
        initial = {
            "BASE": colors[0], "LOVE": colors[1], "ROSE": colors[2],
            "PINE": colors[3], "FOAM": colors[4],
        }

        # 2. Derive the full 51-key palette using the math engine
        full_palette = derive_full_palette(initial)

        # 3. Pack and Cache
        result = {
            "query": query,
            "palette_name": best['text'],
            "tags": best.get('tags', []),
            "palette": full_palette,
            "fetched_at": datetime.now().isoformat()
        }

        cache[cache_key] = result
        save_cache(cache)
        print(f"✅ Cached '{query}' -> {best['text']}")
        return result

    except Exception as e:
        print(f"❌ Error fetching API: {e}", file=sys.stderr)
        return None

def derive_full_palette(mapped: dict) -> dict:
    """Takes a dict with BASE, LOVE, ROSE, PINE, FOAM and derives the full depth."""
    mode = _theme_mode(mapped["BASE"])
    is_dark = mode == "dark"

    def _to_rgb(h_str):
        h = h_str.lstrip('#')
        return f"{int(h[0:2],16)},{int(h[2:4],16)},{int(h[4:6],16)}"

    # --- 1. STRUCTURAL DEPTH ---
    # Larger L gaps (9%/17% vs 5%/10%) and wider hue shift (9°/16° vs 3.6°/7.2°) so each
    # elevation is visually distinct even at low saturation.
    surface_l = 0.09 if is_dark else -0.08
    overlay_l = 0.17 if is_dark else -0.18

    mapped["SURFACE"] = _adjust(mapped["BASE"], l=surface_l, s=0.03, h=-0.025 if is_dark else 0.025)
    mapped["OVERLAY"] = _adjust(mapped["BASE"], l=overlay_l, s=0.06, h=-0.044 if is_dark else 0.044)
    mapped["OVERLAY_RGB"] = _to_rgb(mapped["OVERLAY"])

    # --- 2. HIGHLIGHTS ---
    h_step = 0.12 if is_dark else -0.12
    mapped["HIGHLIGHT_LOW"]  = _adjust(mapped["BASE"], l=h_step)
    mapped["HIGHLIGHT_MED"]  = _adjust(mapped["BASE"], l=h_step * 1.6, s=0.05)
    mapped["HIGHLIGHT_HIGH"] = _adjust(mapped["BASE"], l=h_step * 2.2, s=0.10)

    # --- 3. TEXT HIERARCHY ---
    mapped["TEXT"] = _get_text_color(mapped["BASE"])
    mapped["TEXT_PRIMARY"] = mapped["TEXT"]
    mapped["TEXT_SECONDARY"] = _adjust(mapped["TEXT"], l=-0.25 if is_dark else 0.25, s=-0.1)
    mapped["SUBTLE"] = _adjust(mapped["BASE"], l=0.3 if is_dark else -0.3, s=-0.05)
    mapped["MUTED"] = _adjust(mapped["BASE"], l=0.15 if is_dark else -0.15, s=-0.1)
    mapped["MUTED_ICON"] = _adjust(mapped["BASE"], l=0.20 if is_dark else -0.20)

    # --- 4. HARMONIC ACCENTS ---
    # Tint + small hue shift from the input team colors — no large hue jumps.
    # IRIS: cool-accent slot; nudge FOAM slightly toward violet.
    # GOLD: warm-amber slot; pick whichever of LOVE/ROSE/PINE is closest to
    #       orange (H≈0.08) and nudge it further toward amber.
    mapped["IRIS"] = _adjust(mapped["FOAM"], h=0.06, s=0.05)

    def _circ_dist(a, b):
        d = abs(a - b) % 1.0
        return min(d, 1.0 - d)

    warm_key = min(["LOVE", "ROSE", "PINE"],
                   key=lambda k: _circ_dist(_hex_to_hsl(mapped[k])[0], 0.08))
    wh, ws, wl = _hex_to_hsl(mapped[warm_key])
    # Nudge 25% toward orange (H=0.08) using the correct circular direction
    gold_diff = (0.08 - wh + 0.5) % 1.0 - 0.5
    mapped["GOLD"] = _hsl_to_hex(
        (wh + gold_diff * 0.25) % 1.0,
        max(0.0, min(1.0, ws - 0.05)),
        max(0.0, min(1.0, wl + (0.08 if is_dark else -0.08))),
    )

    # Ensure readability
    for acc in ["LOVE", "PINE", "FOAM", "IRIS", "GOLD", "ROSE"]:
        _, _, al = _hex_to_hsl(mapped[acc])
        if is_dark and al < 0.4: mapped[acc] = _adjust(mapped[acc], l=0.2, s=0.1)
        if not is_dark and al > 0.7: mapped[acc] = _adjust(mapped[acc], l=-0.2, s=0.1)

    # --- 5. UNIFIED HOVERS ---
    h_lift = 0.15 if is_dark else -0.15
    mapped["HOVER_BG"] = _adjust(mapped["BASE"], l=h_lift, s=0.05)
    for key in ["MUTED", "FOAM", "PINE", "GOLD", "LOVE", "ROSE", "IRIS"]:
        mapped[f"HOVER_{key}_BG"] = _adjust(mapped[key], l=h_lift, s=0.1)

    # Legacy hover aliases
    mapped["HOVER_TEAL_BG"]   = mapped["HOVER_FOAM_BG"]
    mapped["HOVER_GREEN_BG"]  = mapped["HOVER_PINE_BG"]
    mapped["HOVER_GOLD_BG"]   = mapped["HOVER_GOLD_BG"]
    mapped["HOVER_ORANGE_BG"] = _adjust(mapped["LOVE"], h=0.05, l=h_lift)

    # --- 6. GHOSTTY INVERSE ---
    if is_dark:
        mapped["GHOSTTY_BG"] = _adjust(mapped["GOLD"], l=0.4, s=-0.15)
        mapped["GHOSTTY_FG"] = _adjust(mapped["BASE"], l=-0.1)
    else:
        mapped["GHOSTTY_BG"] = _adjust(mapped["PINE"], l=-0.5, s=0.2)
        mapped["GHOSTTY_FG"] = _adjust(mapped["BASE"], l=0.4)

    # --- 7. WAYBAR & SHADOWS ---
    mapped["WB_BASE"] = _adjust(mapped["BASE"], l=surface_l * 0.5)
    mapped["WB_SURFACE"] = mapped["SURFACE"]
    mapped["WB_OVERLAY"] = mapped["OVERLAY"]

    for t in ["BASE", "SURFACE", "OVERLAY"]:
        target = mapped[t]
        mapped[f"GRAD_{t}_HI"] = _adjust(target, l=0.04, s=0.02)
        mapped[f"GRAD_{t}_LO"] = _adjust(target, l=-0.04, s=-0.02)

    mapped["SHADOW"] = _adjust(mapped["BASE"], l=-0.25 if is_dark else -0.4, s=0.15, h=-0.05)
    mapped["SHADOW_RGB"] = _to_rgb(mapped["SHADOW"])
    mapped["BORDER_ACCENT_RGB"] = _to_rgb(mapped["LOVE"])
    mapped["BORDER_IRIS_RGB"] = _to_rgb(mapped["IRIS"])
    mapped["INACTIVE_BORDER"] = mapped["MUTED"]
    mapped["BORDER_ACCENT"] = _adjust(mapped["LOVE"], l=-0.05)

    # --- 8. TINTS & STATES ---
    mapped["TINT_PINE_DARK"] = _adjust(mapped["PINE"], l=-0.2)
    mapped["TINT_PINE_MID"] = _adjust(mapped["PINE"], l=-0.1)
    mapped["TINT_CRITICAL_BG"] = _adjust(mapped["LOVE"], l=0.2 if is_dark else -0.2, s=-0.2)
    mapped["WARNING"] = _adjust(mapped["LOVE"], h=0.05)
    mapped["CRITICAL"] = mapped["LOVE"]
    mapped["CAUTION"] = mapped["GOLD"]

    # --- 9. ROLE MAPPINGS ---
    mapped.update({
        "BATTERY_CRIT": mapped["LOVE"], "BATTERY_LOW": mapped["GOLD"],
        "BATTERY_MED": mapped["ROSE"], "BATTERY_HIGH": mapped["FOAM"],
        "BATTERY_FULL": mapped["PINE"], "ACCENT_PRIMARY": mapped["IRIS"],
        "ACCENT_SECONDARY": mapped["FOAM"]
    })

    return mapped

def save_cache(cache: dict):
    """Saves the current API palette cache to a JSON file."""
    with open(API_CACHE_FILE, 'w') as f:
        json.dump(cache, f, indent=2)

def load_cache() -> dict:
    """Loads the API palette cache if it exists."""
    if API_CACHE_FILE.exists():
        try:
            with open(API_CACHE_FILE, 'r') as f:
                return json.load(f)
        except Exception:
            return {}
    return {}
# ── File Generators ───────────────────────────────────────────────────────────

def _read_sh_palette(sh_path: Path) -> dict:
    """Parse a palette.sh file back into a dict of exported variables."""
    palette = {}
    for line in sh_path.read_text().splitlines():
        if line.startswith('export '):
            rest = line[7:]
            if '=' in rest:
                key, _, val = rest.partition('=')
                palette[key.strip()] = val.strip().strip('"')
    return palette

def slugify(name: str) -> str:
    name = unicodedata.normalize("NFKD", name)
    name = name.encode("ascii", "ignore").decode()
    name = name.lower().strip()
    name = re.sub(r"[^a-z0-9]+", "-", name)
    return name.strip("-")

def write_nix(path: Path, p: dict, name: str):
    path.write_text(f"""\
{{
  # ── Base ──────────────────────────────────────────────────────
  BASE           = "{p['BASE']}";
  SURFACE        = "{p['SURFACE']}";
  OVERLAY        = "{p['OVERLAY']}";
  HIGHLIGHT_LOW  = "{p['HIGHLIGHT_LOW']}";
  HIGHLIGHT_MED  = "{p['HIGHLIGHT_MED']}";
  HIGHLIGHT_HIGH = "{p['HIGHLIGHT_HIGH']}";

  # ── Text & accents ────────────────────────────────────────────
  MUTED  = "{p['MUTED']}";
  SUBTLE = "{p['SUBTLE']}";
  TEXT   = "{p['TEXT']}";
  LOVE   = "{p['LOVE']}";
  ROSE   = "{p['ROSE']}";
  GOLD   = "{p['GOLD']}";
  PINE   = "{p['PINE']}";
  FOAM   = "{p['FOAM']}";
  IRIS   = "{p['IRIS']}";

  # ── Extended ──────────────────────────────────────────────────
  CRITICAL   = "{p['CRITICAL']}";
  WARNING    = "{p['WARNING']}";
  CAUTION    = "{p['CAUTION']}";
  MUTED_ICON = "{p['MUTED_ICON']}";

  # ── Structural ────────────────────────────────────────────────
  INACTIVE_BORDER = "{p['INACTIVE_BORDER']}";
  SHADOW          = "{p['SHADOW']}";

  # ── Waybar ────────────────────────────────────────────────────
  WB_BASE    = "{p['WB_BASE']}";
  WB_SURFACE = "{p['WB_SURFACE']}";
  WB_OVERLAY = "{p['WB_OVERLAY']}";

  # ── Gradients ─────────────────────────────────────────────────
  GRAD_SURFACE_HI = "{p['GRAD_SURFACE_HI']}";
  GRAD_SURFACE_LO = "{p['GRAD_SURFACE_LO']}";
  GRAD_OVERLAY_HI = "{p['GRAD_OVERLAY_HI']}";
  GRAD_OVERLAY_LO = "{p['GRAD_OVERLAY_LO']}";
  GRAD_BASE_HI    = "{p['GRAD_BASE_HI']}";
  GRAD_BASE_LO    = "{p['GRAD_BASE_LO']}";

  # ── Borders ───────────────────────────────────────────────────
  BORDER_ACCENT_RGB = "{p['BORDER_ACCENT_RGB']}";
  BORDER_IRIS_RGB   = "{p['BORDER_IRIS_RGB']}";

  # ── Tints ─────────────────────────────────────────────────────
  TINT_PINE_DARK   = "{p['TINT_PINE_DARK']}";
  TINT_PINE_MID    = "{p['TINT_PINE_MID']}";
  TINT_CRITICAL_BG = "{p['TINT_CRITICAL_BG']}";

  # ── Hovers ────────────────────────────────────────────────────
  HOVER_MUTED_BG  = "{p['HOVER_MUTED_BG']}";
  HOVER_TEAL_BG   = "{p['HOVER_TEAL_BG']}";
  HOVER_GREEN_BG  = "{p['HOVER_GREEN_BG']}";
  HOVER_GOLD_BG   = "{p['HOVER_GOLD_BG']}";
  HOVER_ORANGE_BG = "{p['HOVER_ORANGE_BG']}";

  # ── Typography ────────────────────────────────────────────────
  FONT_SIZE_BAR = "{p.get('FONT_SIZE_BAR', '12px')}";
  ICON_SHADOW   = "{p.get('ICON_SHADOW', '0 1px 2px rgba(0,0,0,0.80)')}";

  # ── Shadows ───────────────────────────────────────────────────
  SHADOW_RGB     = "{p['SHADOW_RGB']}";
  SHADOW_A_OUTER = "0.50";
  SHADOW_A_DROP  = "0.55";
  SHADOW_A_HOVER = "0.65";
  INSET_TOP_A    = "0.08";
  INSET_BOT_A    = "0.30";
  BORDER_TOP_A   = "0.07";

  # ── Battery ───────────────────────────────────────────────────
  BATTERY_FULL = "{p['BATTERY_FULL']}";
  BATTERY_HIGH = "{p['BATTERY_HIGH']}";
  BATTERY_MED  = "{p['BATTERY_MED']}";
  BATTERY_LOW  = "{p['BATTERY_LOW']}";
  BATTERY_CRIT = "{p['BATTERY_CRIT']}";

  # ── Roles ─────────────────────────────────────────────────────
  BORDER_ACCENT    = "{p['BORDER_ACCENT']}";
  ACCENT_PRIMARY   = "{p['ACCENT_PRIMARY']}";
  TEXT_PRIMARY     = "{p['TEXT_PRIMARY']}";
  TEXT_SECONDARY   = "{p['TEXT_SECONDARY']}";
  ACCENT_SECONDARY = "{p['ACCENT_SECONDARY']}";
}}
""")

def write_sh(path: Path, p: dict, name: str):
    """Writes a full shell-compatible palette for Waybar and wallpaper scripts."""
    lines = [
        "#!/usr/bin/env bash",
        f"# {name} — generated palette",
        "",
        "# --- All Theme Variables ---"
    ]

    # Export every key found in the palette dictionary
    for key, value in p.items():
        lines.append(f'export {key}="{value}"')

    # Ensure explicit wallpaper mapping is also present
    lines.extend([
        "",
        "# --- Wallpaper Mapping ---",
        f'export BG_DARK="{p.get("BASE", "#1a1a1a")}"',
        f'export BG_LIGHT="{p.get("SURFACE", "#2a2a2a")}"',
        f'export ICE_SHADOW="{p.get("BASE", "#1a1a1a")}"',
        f'export ICE_MID="{p.get("LOVE", p.get("ROSE", "#ff00ff"))}"',
        f'export ICE_HIGHLIGHT="{p.get("FOAM", p.get("IRIS", "#ffffff"))}"',
        f'export CONE_SHADOW="{p.get("GOLD", "#965a28")}"',
        f'export CONE_MID="{p.get("ROSE", "#d28e46")}"',
        'export STICKER_COLOR="#ffffff"'
    ])

    path.write_text("\n".join(lines) + "\n")
    path.chmod(0o755)

def write_kate(path: Path, p: dict, name: str):
    """
    Generates a KDE Color Scheme (.colors) and Syntax Highlighting (.xml) for Kate.
    """
    # FIX: Ensure the directory exists before writing files
    path.mkdir(parents=True, exist_ok=True)

    slug = slugify(name)

    # 1. Generate the Color Scheme (.colors)
    colors_content = f"""[General]
Name={name}

[Colors]
BackgroundNormal={p['BASE']}
BackgroundSelection={p['HIGHLIGHT_MED']}
BackgroundInactive={p['SURFACE']}
ForegroundNormal={p['TEXT']}
ForegroundSelection={p['TEXT']}
ForegroundInactive={p['MUTED']}
ForegroundLink={p['FOAM']}
ForegroundVisited={p['ROSE']}
ForegroundNegative={p['CRITICAL']}
ForegroundNeutral={p['GOLD']}
ForegroundPositive={p['PINE']}
ForegroundNotice={p['IRIS']}
Cursor={p['LOVE']}
CursorText={p['TEXT']}
SelectionBackground={p['HIGHLIGHT_MED']}
SelectionForeground={p['TEXT']}
HighlightWord={p['OVERLAY']}
MatchBackground={p['GOLD']}
MatchForeground={p['BASE']}

[View]
LineNumbers={p['MUTED']}
CurrentLine={p['OVERLAY']}
BracketMatching={p['IRIS']}
SearchHighlight={p['GOLD']}
SearchHighlightCurrent={p['LOVE']}
WordWrapMarker={p['SUBTLE']}
ModifiedLine={p['ROSE']}
SavedLine={p['PINE']}
"""

    # 2. Generate Syntax Highlighting (.xml)
    syntax_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="{name}" version="1.0" kateversion="5.0" section="Sources" extensions="" mimetype="" priority="0">
  <highlighting>
    <list name="keywords">
      <item>def</item><item>class</item><item>return</item><item>if</item><item>else</item>
      <item>for</item><item>while</item><item>import</item><item>from</item><item>pass</item>
      <item>True</item><item>False</item><item>None</item><item>and</item><item>or</item><item>not</item>
    </list>
    <contexts>
      <context name="Normal" attribute="Normal Text" lineEndContext="#stay">
        <Keyword attribute="Keyword" context="#stay" String="keywords" />
        <Float attribute="Float" context="#stay" />
        <Int attribute="Decimal" context="#stay" />
        <String attribute="String" context="#stay" />
        <DetectChar attribute="Comment" context="Comment" char="#" />
        <RegExpr attribute="Function" context="#stay" String="[a-zA-Z_][a-zA-Z0-9_]*(?=\\()" />
      </context>
      <context name="Comment" attribute="Comment" lineEndContext="#pop">
        <IncludeRules context="##Alerts" />
      </context>
    </contexts>
    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal" spellChecking="false" />
      <itemData name="Keyword" defStyleNum="dsKeyword" color="{p['IRIS']}" selColor="{p['HIGHLIGHT_MED']}" />
      <itemData name="Function" defStyleNum="dsFunction" color="{p['FOAM']}" selColor="{p['HIGHLIGHT_MED']}" />
      <itemData name="Decimal" defStyleNum="dsDecVal" color="{p['GOLD']}" selColor="{p['HIGHLIGHT_MED']}" />
      <itemData name="Float" defStyleNum="dsFloat" color="{p['GOLD']}" selColor="{p['HIGHLIGHT_MED']}" />
      <itemData name="String" defStyleNum="dsString" color="{p['PINE']}" selColor="{p['HIGHLIGHT_MED']}" />
      <itemData name="Comment" defStyleNum="dsComment" color="{p['MUTED']}" selColor="{p['HIGHLIGHT_MED']}" />
      <itemData name="Alert" defStyleNum="dsAlert" color="{p['CRITICAL']}" selColor="{p['HIGHLIGHT_MED']}" />
    </itemDatas>
  </highlighting>
  <general>
    <keywords weakDeliminator="" />
    <indentation mode="normal" />
  </general>
</language>
"""

    # Write the files
    colors_path = path / f"kate-{slug}.colors"
    colors_path.write_text(colors_content)

    syntax_path = path / f"kate-{slug}-syntax.xml"
    syntax_path.write_text(syntax_content)

    return colors_path, syntax_path

def write_nemo(path: Path, p: dict, name: str):
    """
    Generates a comprehensive Nemo CSS theme.
    Overrides global GTK styles with specific selectors and !important flags.
    """
    content = f"""/* Nemo Theme: {name} — Auto-generated by auto-theme.py */

/* 1. Define Global Variables for GTK inheritance */
@define-color nemo_base_bg {p['BASE']};
@define-color nemo_surface_bg {p['SURFACE']};
@define-color nemo_overlay_bg {p['OVERLAY']};
@define-color nemo_text {p['TEXT']};
@define-color nemo_muted {p['MUTED']};
@define-color nemo_subtle {p['SUBTLE']};
@define-color nemo_love {p['LOVE']};
@define-color nemo_iris {p['IRIS']};
@define-color nemo_gold {p['GOLD']};
@define-color nemo_pine {p['PINE']};
@define-color nemo_foam {p['FOAM']};
@define-color nemo_critical {p['CRITICAL']};
@define-color nemo_hl_low {p['HIGHLIGHT_LOW']};
@define-color nemo_hl_med {p['HIGHLIGHT_MED']};

/* 2. Main Window */
.nemo-window {{
    background-color: @nemo_base_bg !important;
    color: @nemo_text !important;
}}

/* 3. Sidebar (Places, Tree, etc.) */
.nemo-places-sidebar,
.nemo-tree-sidebar {{
    background-color: @nemo_surface_bg !important;
    color: @nemo_text !important;
}}

/* Selected item in sidebar */
.nemo-places-sidebar .sidebar-row:selected,
.nemo-tree-sidebar .sidebar-row:selected {{
    background-color: alpha(@nemo_love, 0.25) !important;
    color: @nemo_text !important;
    border-left: 3px solid @nemo_love !important;
}}

/* Hover in sidebar */
.nemo-places-sidebar .sidebar-row:hover,
.nemo-tree-sidebar .sidebar-row:hover {{
    background-color: alpha(@nemo_overlay_bg, 0.3) !important;
}}

/* 4. Main File View (Icon/List view) */
.nemo-window .view,
.nemo-window .icon-view {{
    background-color: @nemo_base_bg !important;
    color: @nemo_text !important;
}}

/* Selected files in main view */
.nemo-window .view:selected,
.nemo-window .icon-view:selected {{
    background-color: alpha(@nemo_love, 0.3) !important;
    color: @nemo_text !important;
    border-radius: 4px;
}}

/* Hover in main view */
.nemo-window .view:hover,
.nemo-window .icon-view:hover {{
    background-color: alpha(@nemo_overlay_bg, 0.2) !important;
}}

/* 5. Status Bar */
.nemo-window .statusbar {{
    background-color: @nemo_surface_bg !important;
    color: @nemo_muted !important;
    border-top: 1px solid @nemo_overlay_bg !important;
}}

/* 6. Toolbar & Path Bar */
.nemo-window .toolbar {{
    background-color: @nemo_surface_bg !important;
    border-bottom: 1px solid @nemo_overlay_bg !important;
}}

.nemo-window .toolbar button {{
    color: @nemo_text !important;
    background-color: transparent !important;
    border: 1px solid transparent !important;
}}

.nemo-window .toolbar button:hover {{
    background-color: @nemo_overlay_bg !important;
    border-color: @nemo_subtle !important;
}}

.nemo-window .toolbar button:checked {{
    background-color: @nemo_love !important;
    color: @nemo_text !important;
}}

/* Path Bar Buttons */
.nemo-window .path-bar button {{
    color: @nemo_text !important;
    background-color: @nemo_surface_bg !important;
    border: 1px solid @nemo_overlay_bg !important;
}}

.nemo-window .path-bar button:hover {{
    background-color: @nemo_overlay_bg !important;
}}

.nemo-window .path-bar button:checked {{
    background-color: @nemo_love !important;
    color: @nemo_text !important;
}}

/* 7. Entry Fields (Search, Location) */
.nemo-window entry {{
    background-color: @nemo_surface_bg !important;
    color: @nemo_text !important;
    border: 1px solid @nemo_overlay_bg !important;
}}

.nemo-window entry:focus {{
    border-color: @nemo_iris !important;
    box-shadow: inset 0 0 0 1px @nemo_iris !important;
}}

/* 8. Scrollbars */
.nemo-window scrollbar {{
    background-color: @nemo_base_bg !important;
}}

.nemo-window scrollbar slider {{
    background-color: @nemo_muted !important;
    border-radius: 4px;
}}

.nemo-window scrollbar slider:hover {{
    background-color: @nemo_subtle !important;
}}

.nemo-window scrollbar slider:active {{
    background-color: @nemo_love !important;
}}

/* ═══════════════════════════════════════════════════════════
 * Deluge — same palette, broad selectors (no app CSS class)
 * ═══════════════════════════════════════════════════════════ */

window {{
    background-color: @nemo_base_bg;
    color: @nemo_text;
}}

treeview {{
    background-color: @nemo_base_bg;
    color: @nemo_text;
}}

treeview row:hover {{
    background-color: @nemo_hl_low;
}}

treeview row:selected,
treeview row:selected:focus {{
    background-color: alpha(@nemo_iris, 0.25);
    color: @nemo_text;
}}

treeview header button {{
    background-color: @nemo_surface_bg;
    color: @nemo_subtle;
    border-right: 1px solid @nemo_overlay_bg;
    border-bottom: 1px solid @nemo_overlay_bg;
    padding: 3px 6px;
}}

treeview header button:hover {{
    background-color: @nemo_overlay_bg;
    color: @nemo_text;
}}

/* Download/upload progress bars in torrent list cells */
progressbar trough {{
    background-color: @nemo_overlay_bg;
    border-radius: 3px;
    min-height: 6px;
}}

progressbar progress {{
    background-color: @nemo_pine;
    border-radius: 3px;
}}

/* Detail tabs: Files / Peers / Trackers / Options */
notebook > header {{
    background-color: @nemo_surface_bg;
    border-bottom: 1px solid @nemo_overlay_bg;
}}

notebook > header > tabs > tab {{
    color: @nemo_muted;
    padding: 4px 12px;
    border-radius: 5px 5px 0 0;
}}

notebook > header > tabs > tab:hover {{
    color: @nemo_subtle;
    background-color: alpha(@nemo_overlay_bg, 0.5);
}}

notebook > header > tabs > tab:checked {{
    background-color: @nemo_base_bg;
    color: @nemo_iris;
    border-bottom: 2px solid @nemo_iris;
}}

/* Toolbar: Add / Remove / Pause / Resume buttons */
toolbar {{
    background-color: @nemo_surface_bg;
    border-bottom: 1px solid @nemo_overlay_bg;
    padding: 2px;
}}

toolbar button {{
    color: @nemo_subtle;
    background-color: transparent;
    border: 1px solid transparent;
    border-radius: 5px;
}}

toolbar button:hover {{
    color: @nemo_text;
    background-color: @nemo_overlay_bg;
}}

toolbar button:active,
toolbar button:checked {{
    background-color: alpha(@nemo_iris, 0.2);
    color: @nemo_iris;
}}

statusbar {{
    background-color: @nemo_surface_bg;
    border-top: 1px solid @nemo_overlay_bg;
    color: @nemo_muted;
    font-size: 11px;
    padding: 2px 8px;
}}

entry {{
    background-color: @nemo_surface_bg;
    color: @nemo_text;
    border: 1px solid @nemo_overlay_bg;
    border-radius: 4px;
    padding: 3px 6px;
}}

entry:focus {{
    border-color: @nemo_iris;
}}

menu {{
    background-color: @nemo_surface_bg;
    border: 1px solid @nemo_overlay_bg;
    border-radius: 6px;
    padding: 4px;
}}

menu > menuitem {{
    border-radius: 4px;
    color: @nemo_text;
    padding: 3px 10px;
}}

menu > menuitem:hover {{
    background-color: alpha(@nemo_iris, 0.2);
    color: @nemo_text;
}}

menu > separator {{
    background-color: @nemo_overlay_bg;
    margin: 4px 8px;
}}

scrollbar {{
    background-color: transparent;
}}

scrollbar slider {{
    background-color: @nemo_overlay_bg;
    border-radius: 4px;
    min-width: 6px;
    min-height: 6px;
}}

scrollbar slider:hover {{
    background-color: @nemo_subtle;
}}

tooltip {{
    background-color: @nemo_surface_bg;
    border: 1px solid @nemo_overlay_bg;
    border-radius: 6px;
    color: @nemo_text;
}}

tooltip * {{
    color: @nemo_text;
}}
"""
    path.write_text(content)

def write_ghostty(path: Path, p: dict, name: str):
    content = f"""# Ghostty Theme: {name} — auto-generated by auto-theme.py
background = {p['BASE']}
foreground = {p['TEXT']}
cursor-color = {p['LOVE']}
cursor-text = {p['TEXT']}
selection-background = {p['HIGHLIGHT_MED']}
selection-foreground = {p['TEXT']}

# ANSI 0–15 palette
palette = 0={p['BASE']}
palette = 1={p['CRITICAL']}
palette = 2={p['PINE']}
palette = 3={p['GOLD']}
palette = 4={p['IRIS']}
palette = 5={p['ROSE']}
palette = 6={p['FOAM']}
palette = 7={p['MUTED']}
palette = 8={p['SUBTLE']}
palette = 9={p['CRITICAL']}
palette = 10={p['PINE']}
palette = 11={p['GOLD']}
palette = 12={p['IRIS']}
palette = 13={p['ROSE']}
palette = 14={p['FOAM']}
palette = 15={p['HIGHLIGHT_HIGH']}

window-padding-x = 12
window-padding-y = 8
"""
    path.write_text(content)

def write_niri(path: Path, p: dict, name: str):
    # Niri TOML config
    content = f"""# Niri Theme: {name}
[colors]
background = "{p['BASE']}"
text = "{p['TEXT']}"
cursor = "{p['LOVE']}"

[colors.selection]
border = "{p['IRIS']}"
background = "{p['WB_SURFACE']}"

[colors.hints]
start = "{p['GOLD']}"
end = "{p['ROSE']}"
"""
    path.write_text(content)

def write_lix(path: Path, p: dict, name: str):
    # This matches the structure expected by your Nix configuration
    content = f"""{{
  # Generated Lix Palette: {name}
  p = {{
    LOVE = "{p['LOVE']}";
    ROSE = "{p['ROSE']}";
    GOLD = "{p['GOLD']}";
    PINE = "{p['PINE']}";
    FOAM = "{p['FOAM']}";
    IRIS = "{p['IRIS']}";
    # ... add other mapping as needed
  }};
}}"""
    path.write_text(content)

def write_wleave(path: Path, p: dict, name: str):
    content = f"""/* wleave Theme: {name} — auto-generated by auto-theme.py */
* {{
    background-image: none;
    font-family: "JetBrainsMono Nerd Font", monospace;
    font-size: 36px;
}}

window {{
    background-color: {p['BASE']}; /* Dark background */
}}

button {{
    color: {p['TEXT']};
    background-color: {p['SURFACE']};
    border: 2px solid {p['IRIS']};
    border-radius: {LAYOUT['RADIUS_LG']}px;
    margin: 8px;
    outline-style: none;
    box-shadow: none;
    text-shadow: none;
    background-repeat: no-repeat;
    background-position: center 35%;
    background-size: 20%;
    transition: all 0.2s ease-in-out;
}}

button:hover {{
    background-color: {p['HIGHLIGHT_MED']};
    border-color: {p['GOLD']};
    color: {p['TEXT']};
    background-size: 23%;
    outline-style: none;
}}

button:focus {{
    background-color: {p['HIGHLIGHT_MED']};
    border-color: {p['LOVE']};
    outline-style: none;
}}

#lock:hover      {{ border-color: {p['GOLD']}; color: {p['GOLD']}; }}
#logout:hover    {{ border-color: {p['IRIS']}; color: {p['IRIS']}; }}
#suspend:hover   {{ border-color: {p['PINE']}; color: {p['PINE']}; }}
#hibernate:hover {{ border-color: {p['FOAM']}; color: {p['FOAM']}; }}
#shutdown:hover  {{ border-color: {p['LOVE']}; color: {p['LOVE']}; }}
#reboot:hover    {{ border-color: {p['ROSE']}; color: {p['ROSE']}; }}
"""
    path.write_text(content)

def write_fuzzel(path: Path, p: dict, name: str):
    """Generates fuzzel.ini mirroring mkFuzzelIni in home/niri/default.nix."""
    c = lambda hex: hex.lstrip('#') + 'ff'
    content = f"""[main]
font=monospace:size=13
dpi-aware=auto
prompt=
terminal=ghostty -e
layer=overlay
show-actions=yes
width=35
lines=8

[colors]
background={c(p['BASE'])}
text={c(p['TEXT'])}
match={c(p['IRIS'])}
selection={c(p['OVERLAY'])}
selection-text={c(p['ROSE'])}
selection-match={c(p['FOAM'])}
border={c(p['PINE'])}

[border]
width=1
radius={LAYOUT['RADIUS_SM']}
"""
    path.write_text(content)

def write_wleave(path: Path, p: dict, name: str):
    """Generates wleave CSS matching the papercraft aesthetic."""
    content = f"""/* wleave Theme: {name} — auto-generated by auto-theme.py */
* {{
    background-image: none;
    font-family: "JetBrainsMono Nerd Font", monospace;
    font-size: 36px;
}}

window {{
    background-color: rgba({p['SHADOW_RGB']}, 0.9);
}}

button {{
    color: {p['TEXT']};
    background-color: {p['SURFACE']};
    border: 3px solid {p['SHADOW']};
    border-radius: {LAYOUT['RADIUS_LG']}px;
    box-shadow: 5px 6px 0 0 {p['SHADOW']};
    margin: 8px;
    outline-style: none;
    text-shadow: none;
    background-repeat: no-repeat;
    background-position: center 35%;
    background-size: 20%;
    transition: background-color 0.10s ease, box-shadow 0.10s ease, background-size 0.10s ease;
}}

button:hover {{
    background-color: {p['OVERLAY']};
    box-shadow: 3px 4px 0 0 {p['SHADOW']};
    background-size: 23%;
    outline-style: none;
}}

button:focus {{
    background-color: {p['OVERLAY']};
    border-color: {p['IRIS']};
    outline-style: none;
}}

#lock:hover      {{ border-color: {p['FOAM']}; color: {p['FOAM']}; }}
#logout:hover    {{ border-color: {p['LOVE']}; color: {p['LOVE']}; }}
#suspend:hover   {{ border-color: {p['IRIS']}; color: {p['IRIS']}; }}
#hibernate:hover {{ border-color: {p['GOLD']}; color: {p['GOLD']}; }}
#shutdown:hover  {{ border-color: {p['LOVE']}; color: {p['LOVE']}; }}
#reboot:hover    {{ border-color: {p['ROSE']}; color: {p['ROSE']}; }}
"""
    path.write_text(content)

def write_wvkbd(path: Path, p: dict, name: str):
    """Generates wvkbd color args file (sourced by the systemd service at launch)."""
    strip = lambda h: h.lstrip('#')
    content = (
        f'#!/usr/bin/env bash\n'
        f'# wvkbd color args for {name}\n'
        f'WVKBD_ARGS="'
        f'--bg {strip(p["BASE"])} '
        f'--fg {strip(p["WB_SURFACE"])} '
        f'--fg-sp {strip(p["WB_OVERLAY"])} '
        f'--press {strip(p["LOVE"])} '
        f'--press-sp {strip(p["PINE"])} '
        f'--swipe {strip(p["FOAM"])} '
        f'--swipe-sp {strip(p["IRIS"])} '
        f'--text {strip(p["TEXT"])} '
        f'--text-sp {strip(p["SUBTLE"])}"\n'
    )
    path.write_text(content)
    path.chmod(0o755)

def write_waybar_css(path: Path, p: dict, name: str):
    path.write_text(generate_waybar_css(p))

# ── Core Logic ────────────────────────────────────────────────────────────────

def register_theme(name: str, palette: dict, source: str, force: bool = False) -> tuple[str, bool]:
    """Write all theme files and return (slug, already_existed).

    If the theme directory already exists with a palette.sh, that palette is
    used for regenerating derived files instead of the auto-derived one — this
    preserves hand-crafted palettes.  Pass force=True to overwrite everything.
    """
    slug = slugify(name)
    theme_dir = TEAMS_DIR / slug
    already = theme_dir.exists()
    theme_dir.mkdir(parents=True, exist_ok=True)

    existing_sh = theme_dir / f"palette-{slug}.sh"
    if already and existing_sh.exists() and not force:
        palette = _read_sh_palette(existing_sh)
        print(f"  ℹ️  Preserving existing palette for {slug} (use --force to regenerate)")
    else:
        write_nix(theme_dir / f"palette-{slug}.nix", palette, name)
        write_sh(theme_dir / f"palette-{slug}.sh", palette, name)

    write_nemo(theme_dir / "nemo.css", palette, name)
    write_ghostty(theme_dir / "ghostty.conf", palette, name)
    write_niri(theme_dir / "niri.toml", palette, name)
    write_fuzzel(theme_dir / "fuzzel.ini", palette, name)
    write_wleave(theme_dir / "wleave.css", palette, name)
    write_wvkbd(theme_dir / "wvkbd-colors.sh", palette, name)
    write_waybar_css(theme_dir / "waybar-style.css", palette, name)

    kate_colors, kate_syntax = write_kate(theme_dir / "kate", palette, name)
    print(f"  ✅ Generated Kate theme: {name}")



    # Wallpaper Generation
    if MAKE_WALLPAPER.exists():
        print(f"🖼️  Generating wallpaper for {slug}...")
        # cwd ensures we are in your config root when running bash
        result = subprocess.run(["bash", str(MAKE_WALLPAPER), slug], cwd=str(NIXOS_ROOT))
        if result.returncode != 0:
            print(f"⚠️  Wallpaper generation failed (exit {result.returncode})")

    return slug, already

def activate_theme(slug: str, theme_dir: Path) -> None:
    """Activate theme instantly."""
    import shutil
    import time

    palette_sh = theme_dir / f"palette-{slug}.sh"
    state_dir = Path.home() / ".local/state"
    state_dir.mkdir(parents=True, exist_ok=True)

    # ── Waybar palette + CSS ──────────────────────────────────────────────────
    waybar_palette = Path.home() / ".config/waybar/palette.sh"
    waybar_palette.unlink(missing_ok=True)
    shutil.copy2(palette_sh, waybar_palette)

    waybar_css_src = theme_dir / "waybar-style.css"
    waybar_css_dst = Path.home() / ".config/waybar/style.css"
    if waybar_css_src.exists():
        waybar_css_dst.unlink(missing_ok=True)
        shutil.copy2(waybar_css_src, waybar_css_dst)
        print("  → Waybar CSS applied")

    (state_dir / "theme").write_text(slug)

    # --- Kate Activation ---
    kate_colors_src = theme_dir / f"kate-{slugify(slug)}.colors"
    kate_syntax_src = theme_dir / f"kate-{slugify(slug)}-syntax.xml"

    # KDE Color Schemes location
    kate_colors_dst = Path.home() / ".local/share/color-schemes" / f"{slugify(slug)}.colors"
    kate_colors_dst.parent.mkdir(parents=True, exist_ok=True)

    # Kate Syntax location (may vary by version, usually katepart5 or katepart6)
    # We try the most common path first
    kate_syntax_dst = Path.home() / ".local/share/katepart5/syntax" / f"{slugify(slug)}.xml"
    kate_syntax_dst.parent.mkdir(parents=True, exist_ok=True)

    if kate_colors_src.exists():
        kate_colors_dst.unlink(missing_ok=True)
        shutil.copy2(kate_colors_src, kate_colors_dst)
        print(f"  ✅ Installed Kate Color Scheme")

    if kate_syntax_src.exists():
        kate_syntax_dst.unlink(missing_ok=True)
        shutil.copy2(kate_syntax_src, kate_syntax_dst)
        print(f"  ✅ Installed Kate Syntax Highlighting")

    # Restart Kate to apply changes
    subprocess.run(["pkill", "kate"], capture_output=True)
    time.sleep(0.5)

    # ── Wallpaper ─────────────────────────────────────────────────────────────
    wallpapers = sorted(theme_dir.glob("wallpaper-*.png"))
    if wallpapers:
        (state_dir / "wallpaper").write_text(str(wallpapers[0]))
        subprocess.run(["systemctl", "--user", "restart", "swaybg"], capture_output=True)

    # ── Fuzzel ────────────────────────────────────────────────────────────────
    fuzzel_src = theme_dir / "fuzzel.ini"
    fuzzel_dst = Path.home() / ".config/fuzzel/fuzzel.ini"
    if fuzzel_src.exists():
        fuzzel_dst.parent.mkdir(parents=True, exist_ok=True)
        fuzzel_dst.unlink(missing_ok=True)
        shutil.copy2(fuzzel_src, fuzzel_dst)
        print("  → Fuzzel theme applied")

    # ── Ghostty ───────────────────────────────────────────────────────────────
    ghostty_src = theme_dir / "ghostty.conf"
    ghostty_dst = Path.home() / ".config/ghostty/config"
    if ghostty_src.exists():
        ghostty_dst.parent.mkdir(parents=True, exist_ok=True)
        ghostty_dst.unlink(missing_ok=True)
        shutil.copy2(ghostty_src, ghostty_dst)
        subprocess.run(["pkill", "-SIGUSR2", "ghostty"], capture_output=True)
        print("  → Ghostty theme applied (new windows pick it up immediately)")

    # ── GTK3 (Nemo + Deluge) ─────────────────────────────────────────────────
    nemo_css_src = theme_dir / "nemo.css"
    gtk3_css_dst = Path.home() / ".config/gtk-3.0/gtk.css"
    if nemo_css_src.exists():
        gtk3_css_dst.parent.mkdir(parents=True, exist_ok=True)
        gtk3_css_dst.unlink(missing_ok=True)
        shutil.copy2(nemo_css_src, gtk3_css_dst)
        print("  → GTK3 theme applied (Nemo + Deluge; restart apps to pick up)")

    # ── wleave ────────────────────────────────────────────────────────────────
    wleave_css_src = theme_dir / "wleave.css"
    wleave_css_dst = Path.home() / ".config/wleave/style.css"
    if wleave_css_src.exists():
        wleave_css_dst.parent.mkdir(parents=True, exist_ok=True)
        wleave_css_dst.unlink(missing_ok=True)  # remove nix store symlink if present
        shutil.copy2(wleave_css_src, wleave_css_dst)
        print("  → wleave theme applied")

    # ── wvkbd ─────────────────────────────────────────────────────────────────
    wvkbd_src = theme_dir / "wvkbd-colors.sh"
    wvkbd_dst = Path.home() / ".config/wvkbd/colors.sh"
    if wvkbd_src.exists():
        wvkbd_dst.parent.mkdir(parents=True, exist_ok=True)
        wvkbd_dst.unlink(missing_ok=True)
        shutil.copy2(wvkbd_src, wvkbd_dst)
        active = subprocess.run(["systemctl", "--user", "is-active", "wvkbd"], capture_output=True)
        if active.returncode == 0:
            subprocess.run(["systemctl", "--user", "restart", "wvkbd"], capture_output=True)
        print("  → wvkbd theme applied")

    # ── Reload Waybar (CSS first, then full restart) ──────────────────────────
    subprocess.run(["pkill", "-SIGUSR1", "waybar"], capture_output=True)
    subprocess.run(["makoctl", "reload"], capture_output=True)
    time.sleep(0.3)
    subprocess.run(["pkill", "-f", "waybar-weather"], capture_output=True)
    subprocess.run(["pkill", "-SIGUSR2", "waybar"], capture_output=True)

    print(f"  ✅ Activated: {slug}")

# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Auto-generate and activate themes from teams or keywords.")
    parser.add_argument("query", nargs="?", help="Team name or keyword (e.g., 'lakers', 'neapolitan')")
    parser.add_argument("--rose-pine", action="store_true", help="Use official Rose Pine palette")
    parser.add_argument("--manual", metavar="HEX_LIST", help="Manual 5 colors: #base,#love,#rose,#pine,#foam")
    parser.add_argument("--list", action="store_true", help="List available teams")
    parser.add_argument("--list-api", metavar="KEYWORD", help="Preview API results for a keyword")
    parser.add_argument("--register-only", action="store_true", help="Generate files but don't activate")
    parser.add_argument("--force", action="store_true", help="Overwrite existing hand-crafted palette files")
    args = parser.parse_args()

    # 1. PRE-FLIGHT DATA LOADING
    teams = []
    if TEAM_DATA_FILE.exists():
        teams = json.loads(TEAM_DATA_FILE.read_text())
    api_cache = load_cache()

    # 2. GLOBAL HELP CHECK
    # Only show help if NO query is provided AND no special flags are used
    if not args.query and not (args.rose_pine or args.manual or args.list or args.list_api):
        parser.print_help()
        sys.exit(1)

    # 3. FLAG: --list
    if args.list:
        if not teams:
            print("No team data found. Run enrich-teamcolors.py first.")
            return
        col_w = max(len(t["name"]) for t in teams) + 2
        for t in sorted(teams, key=lambda x: x["name"]):
            slug = slugify(t["name"])
            registered = (TEAMS_DIR / slug).exists()
            mark = "✓" if registered else " "
            print(f"  {mark} [{t['league']:10s}]  {t['name']:{col_w}}  {slug}")
        return

    # 4. FLAG: --rose-pine
    if args.rose_pine:
        print("🌹 Using Official Rose Pine Palette...")
        if args.query and "dawn" in args.query.lower():
            name, initial = "Rose Pine Dawn", {
                "BASE": "#faf4ed", "LOVE": "#b4637a", "ROSE": "#d7827e",
                "PINE": "#286983", "FOAM": "#56949f"
            }
        else:
            name, initial = "Rose Pine Official", {
                "BASE": "#191724", "LOVE": "#eb6f92", "ROSE": "#ebbcba",
                "PINE": "#31748f", "FOAM": "#9ccfd8"
            }

        p = derive_full_palette(initial)
        slug, _ = register_theme(name, p, "manual", force=args.force)
        if not args.register_only:
            activate_theme(slug, TEAMS_DIR / slug)
        return

    # 5. FLAG: --manual
    if args.manual:
        codes = args.manual.split(',')
        if len(codes) != 5:
            print("❌ Error: --manual requires exactly 5 hex codes (base,love,rose,pine,foam)")
            return
        initial = {"BASE": codes[0], "LOVE": codes[1], "ROSE": codes[2], "PINE": codes[3], "FOAM": codes[4]}
        p = derive_full_palette(initial)
        slug, _ = register_theme("Manual Theme", p, "manual", force=args.force)
        if not args.register_only:
            activate_theme(slug, TEAMS_DIR / slug)
        return

    # 6. FLAG: --list-api
    if args.list_api:
        res = fetch_api_palette(args.list_api, api_cache)
        if res:
            p = res["palette"]
            print(f"Query: {res['query']} -> {res['palette_name']}")
            print(f"Colors: {', '.join([p['BASE'], p['LOVE'], p['IRIS'], p['GOLD']])}")
        else:
            print("No results found.")
        return

    # 7. SEARCH EXECUTION (Teams first, then API)
    # At this point, we know args.query exists because of the check in step 2.

    # Try Team Match
    team_match = None
    query_slug = slugify(args.query)
    for t in teams:
        team_slugs = [slugify(t["name"])] + [slugify(a) for a in t.get("aliases", [])]
        if query_slug in team_slugs:
            team_match = t
            break

    if team_match:
        print(f"🏆 Found Team: {team_match['name']} ({team_match['league']})")
        p = derive_full_palette(team_match["palette"])
        slug, _ = register_theme(team_match["name"], p, "team", force=args.force)
        if not args.register_only:
            activate_theme(slug, TEAMS_DIR / slug)
        return

    # Try API Match
    print(f"🔍 No team found. Trying API for '{args.query}'...")
    api_result = fetch_api_palette(args.query, api_cache)

    if not api_result:
        print(f"❌ No theme found for '{args.query}'.")
        sys.exit(1)

    p = api_result["palette"]
    theme_name = f"{api_result['query']} - {api_result['palette_name']}"
    slug, _ = register_theme(theme_name, p, "api", force=args.force)

    print(f"  ✅ Generated: {slug}")
    if not args.register_only:
        activate_theme(slug, TEAMS_DIR / slug)

if __name__ == "__main__":
    main()
