# hosts/family/hardware.nix
# Generated by nixos-generate-config — matches actual disk layout on the family machine
{ config, lib, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

 fileSystems."/" = {
    # This points to the NAME of the mapper device created below
    device = "/dev/mapper/cryptroot"; 
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  boot.initrd.luks.devices."cryptroot".device =
    # This MUST be the UUID of the PHYSICAL partition (/dev/sda2)
    # Run 'blkid /dev/sda2' to get this ID if it isn't 0d20425e...
    "/dev/disk/by-uuid/YOUR-FAMILY-LUKS-UUID";

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/YOUR-FAMILY-EFI-UUID";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
