general {
    col.active_border = rgba(a8607799) rgba(8872aa99) 45deg
    col.inactive_border = rgba(26233aff)
}

decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.85
    shadow {
        enabled = true
        range = 20
        render_power = 2
        color = rgba(eb6f9233)
    }
    blur {
        enabled = true
        size = 4
        passes = 2
        noise = 0.02
        contrast = 1.0
        brightness = 1.0
    }
}

misc {
    vrr = 0
    vfr = true
}

layerrule = blur true,         match:namespace waybar
layerrule = ignore_alpha 0.0,  match:namespace waybar
layerrule = blur true,         match:namespace mako
layerrule = ignore_alpha 0.0,  match:namespace mako
layerrule = blur true,         match:namespace wofi
layerrule = ignore_alpha 0.0,  match:namespace wofi
layerrule = blur true,         match:namespace cava-overlay
layerrule = ignore_alpha 0.0,  match:namespace cava-overlay
