general {
    gaps_in = 6
    gaps_out = 12
    border_size = 2
    layout = dwindle
}

master {
    mfact = 0.5
    new_status = slave
}

dwindle {
    pseudotile = true
    preserve_split = true
    force_split = 0
}
