workspace = 1, default:true, name:"Main", layout:dwindle
workspace = 2, name:"Terminals", layout:dwindle
workspace = 3, name:"Code", layout:dwindle
workspace = 4, name:"Comms", layout:master
workspace = 5, name:"Music", layout:master
workspace = 6, name:"Games", layout:monocle
workspace = 7, name:"Web+Overflow", layout:scrolling
workspace = 8, name:"SysAdmin", layout:scrolling
workspace = 9, name:"Creative", layout:master
workspace = 10, name:"Void", layout:monocle
