# Niri Theme: dark chocolate - Dark Chocolate Shades
[colors]
background = "#5b3a29"
text = "#ffffff"
cursor = "#bc8a71"

[colors.selection]
border = "#eae3a4"
background = "#6e412f"

[colors.hints]
start = "#d6b78f"
end = "#a87c6b"
