# Niri Theme: london fog - London Fog Cookie
[colors]
background = "#c2b6c8"
text = "#1a1828"
cursor = "#c4a8d4"

[colors.selection]
border = "#b0a8d0"
background = "#b8b0c8"

[colors.hints]
start = "#e49f5d"
end = "#b498c8"
