# Niri Theme: halloween - Halloween
[colors]
background = "#0e0806"
text = "#ffffff"
cursor = "#c65f1b"

[colors.selection]
border = "#882054"
background = "#20110d"

[colors.hints]
start = "#dc872e"
end = "#c6741b"
