# Niri Theme: bay breeze - Bay Breeze Serenade
[colors]
background = "#4c5b94"
text = "#ffffff"
cursor = "#6979ab"

[colors.selection]
border = "#e0e6ff"
background = "#5269a7"

[colors.hints]
start = "#9c88b5"
end = "#91a2c5"
