# Niri Theme: bali - Scandinavian Herbalist
[colors]
background = "#8ebe7e"
text = "#1a1a1a"
cursor = "#a4c98d"

[colors.selection]
border = "#b1e38c"
background = "#79b86b"

[colors.hints]
start = "#c5c25e"
end = "#90c158"
