# Niri Theme: dark smoke - Dark Smoke Evil Fairy
[colors]
background = "#4a4e54"
text = "#ffffff"
cursor = "#436f9e"

[colors.selection]
border = "#eceff3"
background = "#545b63"

[colors.hints]
start = "#e77e65"
end = "#808d8e"
