# Niri Theme: checkers - Cocoa Checkers Delight
[colors]
background = "#503b26"
text = "#ffffff"
cursor = "#b67553"

[colors.selection]
border = "#f0fa9e"
background = "#63452d"

[colors.hints]
start = "#cab49b"
end = "#c1a27b"
