# Niri Theme: espresso - Espresso Delight
[colors]
background = "#3c2a2a"
text = "#ffffff"
cursor = "#b7765c"

[colors.selection]
border = "#365296"
background = "#4c3335"

[colors.hints]
start = "#9c7f30"
end = "#b79b8f"
