# Niri Theme: burgundy - Lavender and Burgundy
[colors]
background = "#59181d"
text = "#ffffff"
cursor = "#d32232"

[colors.selection]
border = "#a97a92"
background = "#6e1c27"

[colors.hints]
start = "#db4c43"
end = "#913b4b"
