# Niri Theme: earl grey - Earl Grey
[colors]
background = "#b8b9b1"
text = "#1a1a1a"
cursor = "#9c9d9b"

[colors.selection]
border = "#393f36"
background = "#acafa2"

[colors.hints]
start = "#888888"
end = "#7c7e7c"
