# Niri Theme: power rangers - Power Rangers
[colors]
background = "#ff3c00"
text = "#ffffff"
cursor = "#ffb300"

[colors.selection]
border = "#d60022"
background = "#ff421a"

[colors.hints]
start = "#fab22e"
end = "#24ffec"
