# Niri Theme: sunset - Rodeo Sunset
[colors]
background = "#dac6b9"
text = "#1a1a1a"
cursor = "#c0b0a5"

[colors.selection]
border = "#6456d7"
background = "#d3bba7"

[colors.hints]
start = "#cddb52"
end = "#a58e8d"
