# Niri Theme: black
[colors]
background = "#000000"
text = "#ffffff"
cursor = "#574747"

[colors.selection]
border = "#b4afac"
background = "#181616"

[colors.hints]
start = "#6d5959"
end = "#7b6565"
