# Niri Theme: fog - The Fog Is Coming
[colors]
background = "#bbc2c9"
text = "#1a1a1a"
cursor = "#8fabb7"

[colors.selection]
border = "#8c9aca"
background = "#abb4bf"

[colors.hints]
start = "#94ada5"
end = "#a7bcc3"
