# Niri Theme: manchester - Cool Palette
[colors]
background = "#c6102e"
text = "#ffffff"
cursor = "#f5f5f5"

[colors.selection]
border = "#928a86"
background = "#f01459"

[colors.hints]
start = "#f0bb6b"
end = "#f1b341"
