# Niri Theme: hibiscus - Hibiscus Bloom
[colors]
background = "#d76a8d"
text = "#ffffff"
cursor = "#e34571"

[colors.selection]
border = "#ff8448"
background = "#d45475"

[colors.hints]
start = "#dc8e6f"
end = "#e66b96"
