# Niri Theme: tottenham - Tottenham Tide
[colors]
background = "#1d4e72"
text = "#ffffff"
cursor = "#498c9c"

[colors.selection]
border = "#cbe80d"
background = "#206288"

[colors.hints]
start = "#2707ee"
end = "#7cb6b2"
