# Niri Theme: high noon - High Noon
[colors]
background = "#f7c94b"
text = "#1a1a1a"
cursor = "#f5a524"

[colors.selection]
border = "#cfbe17"
background = "#f8cf30"

[colors.hints]
start = "#e28b13"
end = "#f3a62b"
